theme: jekyll-theme-minimal

title: SANSUI | XUNYI
logo: https://sansuiz.github.io/All-SANSUIZ/res/cv/Me.jpg
show_downloads: false
description: Welcome to Linsheng's personal site. Here is my <a href="https://sanzuiz.github.io">Home (2020)</a>.
